ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: web.example.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: web-example-com-tls
     hosts:
       - web.example.com