ingress:
  enabled: true
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: cluster1.infotech-asia.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: cluster1-infotech-asia-com-tls
     hosts:
       - cluster1.infotech-asia.com
